Repository CS2103JAN2018-W10-B3/main, pull requests merged in 2018-04, with the labels that each got.

#89 Code collation
  Collate-TUI.jar
  collate.sh
  collated/functional/jaxony.md
  collated/functional/samzx.md
  collated/functional/tohcheryl.md
  collated/test/jaxony.md
  collated/test/tohcheryl.md
Labels: priority.medium

#87 Phone implementation of order command
  build.gradle
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/orderer/FoodSelector.java
  src/main/java/seedu/address/logic/orderer/OrderManager.java
  src/test/java/seedu/address/logic/commands/OrderCommandTest.java
  src/test/java/seedu/address/logic/orderer/FoodSelectorTest.java
  src/test/java/seedu/address/logic/orderer/OrderManagerTest.java
Labels: enhancement

#95 Updated UserGuide
  README.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: documentation

#108 Updated dev and user docs for order command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/order-command--food-selector.png
  docs/images/order-command--order-manager.png
Labels: documentation

#124 Developer Guide: Added UML diagram for UserProfile
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/~$ModelComponentClassDiagram.pptx
  docs/images/add-command-interactive-start.png
  docs/images/model-component-with-user-profile.png
Labels: documentation

#126 Fix/add interactive
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Prompt.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionAddCommand.java
  src/test/java/seedu/address/model/session/SessionAddCommandTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
Labels: bug

#99 Display basic profile
  build.gradle
  copyright.txt
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/ProfilePictureChangedEvent.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ChangePicCommand.java
  src/main/java/seedu/address/logic/commands/UserConfigCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/food/Address.java
  src/main/java/seedu/address/model/food/Name.java
  src/main/java/seedu/address/model/user/UserProfile.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
  src/main/resources/images/defaultprofilepic.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UserProfilePanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/UserProfilePanelHandle.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/ChangePicCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/UserProfilePanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: enhancement

#109 Updated Project Portfolio Page for Sam Xie
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/samxie.adoc
Labels: documentation

#100 Order command - Food selector now selects food with a distributed probability
  docs/UserGuide.adoc
  docs/images/order-manager.png
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/orderer/FoodSelector.java
  src/test/java/seedu/address/logic/commands/OrderCommandTest.java
  src/test/java/seedu/address/logic/orderer/FoodSelectorTest.java
  src/test/java/seedu/address/testutil/FoodBuilder.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement

#125 Update PPP for Cheryl Toh
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/cheryltoh.adoc
Labels: documentation

#131 New order command - email instead of dialing
  build.gradle
  collated/functional/jaxony.md
  collated/functional/samzx.md
  collated/functional/tohcheryl.md
  collated/test/jaxony.md
  collated/test/samzx.md
  collated/test/tohcheryl.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/order-command-flow-chart.png
  docs/team/samxie.adoc
  profilepic.png
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/orderer/FoodSelector.java
  src/main/java/seedu/address/logic/orderer/OrderManager.java
  src/main/java/seedu/address/logic/parser/OrderCommandParser.java
  src/main/java/seedu/address/model/food/Price.java
  src/main/java/seedu/address/model/food/Rating.java
  src/test/java/seedu/address/logic/commands/OrderCommandTest.java
  src/test/java/seedu/address/logic/orderer/FoodSelectorTest.java
  src/test/java/seedu/address/logic/orderer/OrderManagerTest.java
  src/test/java/seedu/address/logic/parser/OrderCommandParserTest.java
  src/test/java/seedu/address/model/food/RatingTest.java
  unused/OrderManager.java
Labels: documentation, enhancement

#135 Added more documentation for contribution of unsued code
  docs/images/unused--order-command--order-manager.png
  docs/team/samxie.adoc
Labels: documentation

#141 Further updated documentation to reflect current state of the app
  collated/functional/samzx.md
  collated/test/samzx.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/OrderCommand.java
Labels: documentation

#150 Fixed bug and added tests for rating displayString
  src/main/java/seedu/address/model/food/Rating.java
  src/test/java/seedu/address/model/food/RatingTest.java
Labels: bug

#157 Bug fix: Optional fields in AddCommand can now be skipped
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionAddCommand.java
  src/test/java/seedu/address/model/session/SessionTest.java
Labels: bug

#166 Fix bug #165: loop in interactively adding food when food exists already
  src/main/java/seedu/address/model/session/Session.java
Labels: bug, priority.low

#162 Developer Guide: added Chat UI section
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ObjectDiagramChatUI.pptx
  docs/images/object-diagram-chat-ui.png
Labels: documentation

#164 New email gives the restaurant a more detailed email summary of the order request.
  collated/functional/jaxony.md
  collated/functional/samzx.md
  collated/functional/tohcheryl.md
  collated/test/jaxony.md
  collated/test/samzx.md
  collated/test/tohcheryl.md
  src/main/java/seedu/address/logic/orderer/EmailManager.java
  src/main/java/seedu/address/logic/orderer/OrderManager.java
  src/test/java/seedu/address/logic/orderer/EmailManagerTest.java
Labels: enhancement

#167 fixed 0 price and ratings field which resulted in not selecting a food.
  src/main/java/seedu/address/logic/orderer/FoodSelector.java
Labels: bug

#172 Added code to check connection before ordering food.
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/orderer/OrderManager.java
  src/test/java/seedu/address/logic/orderer/EmailManagerTest.java
  src/test/java/seedu/address/logic/orderer/OrderManagerTest.java
Labels: enhancement

#174 Update PPP for Cheryl Toh
  collated/functional/jaxony.md
  collated/functional/samzx.md
  collated/functional/tohcheryl.md
  collated/test/jaxony.md
  collated/test/samzx.md
  collated/test/tohcheryl.md
  collated/unused/samzx.md
  docs/UserGuide.adoc
  docs/team/cheryltoh.adoc
Labels: documentation

#176 Improved documentation
  docs/DeveloperGuide.adoc
  docs/team/jacksonhuang.adoc
Labels: documentation

#175 Code quality update
  collated/functional/jaxony.md
  collated/functional/samzx.md
  collated/functional/tohcheryl.md
  collated/test/samzx.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/order-command-flow-chart.png
  docs/images/orderer--food-selector.png
  docs/images/orderer--order-command.png
  docs/images/orderer--order-manager--unsued.png
  docs/images/orderer--order-manager.png
  docs/images/orderer--sequence.png
  docs/team/samxie.adoc
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/orderer/FoodSelector.java
  src/main/java/seedu/address/logic/orderer/OrderManager.java
  src/main/java/seedu/address/logic/parser/OrderCommandParser.java
  src/main/java/seedu/address/model/food/Rating.java
  src/test/java/seedu/address/logic/commands/OrderCommandTest.java
  src/test/java/seedu/address/logic/orderer/EmailManagerTest.java
  src/test/java/seedu/address/logic/orderer/FoodSelectorTest.java
  src/test/java/seedu/address/logic/orderer/OrderManagerTest.java
Labels: documentation, enhancement, refactor, tests

#177 Fixed name of title to HackEat
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: bug
