Repository CS2103JAN2018-W10-B3/main, pull requests merged in 2018-03, with the labels that each got.

#7 Non functional requirements and glossary
  docs/DeveloperGuide.adoc
Labels: documentation

#9 UI: Red error message in ResultDisplay
  src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
Labels: enhancement

#19 Email and Address fields are now optional in "add" command | resolves #10
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: enhancement

#26 Updated README.adoc: landing page for users
  README.adoc
  docs/images/Ui.png
Labels: documentation

#36 `add command` optional fields: address and email, test cases + refactoring | resolves #34
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/FoodBuilder.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: tests

#45 Price is now displayed in UI
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/FoodCard.java
  src/main/resources/view/FoodListCard.fxml
Labels: bug

#43 Feature contributions added. Including major/minor and who's in charge.
  docs/DeveloperGuide.adoc
Labels: documentation

#50 Enhancement rating system
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/Rating.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedFood.java
  src/main/java/seedu/address/ui/FoodCard.java
  src/main/resources/view/FoodListCard.fxml
  src/test/data/XmlSerializableAddressBookTest/typicalFoodsAddressBook.xml
  src/test/data/XmlUtilTest/invalidFoodField.xml
  src/test/data/XmlUtilTest/missingFoodField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validFood.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/food/RatingTest.java
  src/test/java/seedu/address/storage/XmlAdaptedFoodTest.java
  src/test/java/seedu/address/testutil/EditFoodDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FoodBuilder.java
  src/test/java/seedu/address/testutil/FoodUtil.java
  src/test/java/seedu/address/testutil/TypicalFoods.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: enhancement

#52 Refactor default values of food properties
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/food/Address.java
  src/main/java/seedu/address/model/food/Email.java
  src/main/java/seedu/address/model/food/Price.java
  src/main/java/seedu/address/model/food/Rating.java
  src/test/java/seedu/address/testutil/FoodBuilder.java
Labels: refactor

#51 Display price with $ sign in the UI
  src/main/java/seedu/address/model/food/Price.java
  src/main/java/seedu/address/ui/FoodCard.java
Labels: bug, enhancement

#53 Order command developer documentation
  docs/DeveloperGuide.adoc
  docs/images/order-command-flow-chart.png
Labels: documentation

#54 Changed ordering of food card, ratings then price should be first.
  src/main/resources/view/FoodListCard.fxml
Labels: enhancement

#59 Update diagram in Developer Guide
  docs/images/UpdatedLogicCommandClassDiagram.PNG
Labels: documentation

#61 Updated developer guide for implementation of UserConfigCommand
  docs/DeveloperGuide.adoc
Labels: documentation

#60 Add and Edit of User Profile
  src/main/java/seedu/address/logic/commands/UserConfigCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UserConfigCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/food/allergy/Allergy.java
  src/main/java/seedu/address/model/food/allergy/UniqueAllergyList.java
  src/main/java/seedu/address/model/user/UserProfile.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedAllergy.java
  src/main/java/seedu/address/storage/XmlAdaptedUserProfile.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/data/XmlSerializableAddressBookTest/typicalFoodsAddressBook.xml
  src/test/data/XmlUtilTest/tempAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalFoods.java
Labels: enhancement

#73 Order command - base command implemented
  src/main/java/seedu/address/logic/commands/OrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OrderCommandParser.java
  src/test/java/seedu/address/logic/commands/OrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/OrderCommandParserTest.java
Labels: enhancement

#74 Changed logo to something more relevant
  copyright.txt
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/hackeat_logo_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: enhancement

#75 Added order command to user guide
  docs/UserGuide.adoc
Labels: documentation

#80 Amended sample food data util
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug
